language: node_js
node_js:
  - "9"
branches:
  only:
  - master
cache:
  yarn: true
  directories:
    - node_modules
before_install:
- npm i typescript -g
- npm i rimraf -g
script:
- yarn
- yarn compile
- ls -la dist
- yarn pack
- tar -tvf *.tgz
# - TODO: rename file
# deploy:
#   provider: releases
#   api_key: "GITHUB OAUTH TOKEN"
#   file: file
#   skip_cleanup: true
